# -*- coding: utf-8 -*-
"""Bgaian1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e18bsxB7P2My5s2aW5RxSRaPHqUYxetJ
"""

#install package tabulate nya
!pip install tabulate

#import tabulate
from tabulate import tabulate

#assign datanya
id = [1,2,3,4,5,6,7,8,9,10]
angka = ['dua', 'empat', 'delapan', 'lima', 'tujuh', 'satu', 'tiga', 'enam', 'sepuluh', 'sembilan']

#update dictionary nya
angka = [2,4,8,5,7,1,3,6,10,9]
print(angka)

#tampilkan tabelnya
d = {'id' : id,
    'angka' : angka}

print(tabulate(d, headers='keys', tablefmt="grid"))

#function untuk sortir ganjil-genap
for i in angka:
  if i % 2 == 0:  
    print(f"ID {id[angka.index(i)]} merupakan bilangan genap")
  else :
    print(f"ID {id[angka.index(i)]} merupakan bilangan ganjil")

#hapus bilangan ganjil
print(id)
for i in reversed(angka):
  if i & 1:
    id.remove(angka.index(i)+1)
    angka.remove(i)
  else :
    pass

print(tabulate(d, headers='keys', tablefmt="grid"))

#hapus bilangan genap
print(id)
for i in reversed(angka):
  if i & 1:
    pass
  else :
    id.remove(angka.index(i)+1)
    angka.remove(i)

print(tabulate(d, headers='keys', tablefmt="grid"))

